spring.application.name=macros

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/macrofit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true


spring.datasource.username=admin_macrofit
spring.datasource.password=password123


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true